"""Local, ignored provider configuration for the developer-hosted demo."""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path

from code_navi.paths import application_data_dir
from code_navi.providers import ProviderConfigurationError

CONFIG_RELATIVE_PATH = Path(".code-navi") / "provider.env"
_ALLOWED_KEYS = {
    "CODE_NAVI_PROVIDER",
    "CODE_NAVI_MODEL",
    "OPENAI_API_KEY",
    "DEEPSEEK_API_KEY",
    "DEEPSEEK_MODEL",
    "DEEPSEEK_BASE_URL",
}


@dataclass(frozen=True, slots=True)
class LocalProviderConfig:
    """Validated values written to the ignored provider environment file."""

    provider: str
    api_key: str
    model: str | None = None
    base_url: str | None = None

    def __post_init__(self) -> None:
        if self.provider not in {"deepseek", "openai"}:
            raise ProviderConfigurationError("provider must be deepseek or openai")
        for name, value in (
            ("api_key", self.api_key),
            ("model", self.model),
            ("base_url", self.base_url),
        ):
            if value is not None and (not value.strip() or "\n" in value or "\r" in value):
                raise ProviderConfigurationError(f"{name} must be one non-empty line")
        if self.provider == "openai" and not self.model:
            raise ProviderConfigurationError("OpenAI configuration requires --model")
        if not is_plausible_api_key(self.api_key):
            raise ProviderConfigurationError(
                "API key appears incomplete; paste the full provider key"
            )

    def environment(self) -> dict[str, str]:
        values = {"CODE_NAVI_PROVIDER": self.provider}
        if self.provider == "deepseek":
            values["DEEPSEEK_API_KEY"] = self.api_key
            if self.model:
                values["DEEPSEEK_MODEL"] = self.model
            if self.base_url:
                values["DEEPSEEK_BASE_URL"] = self.base_url
        else:
            values["OPENAI_API_KEY"] = self.api_key
            values["CODE_NAVI_MODEL"] = self.model or ""
        return values


def provider_config_path(project_root: Path | None = None) -> Path:
    """Return the explicit override path or the project-local ignored path."""
    override = os.getenv("CODE_NAVI_PROVIDER_CONFIG")
    if override:
        return Path(override).expanduser().resolve()
    return application_data_dir(project_root) / "provider.env"


def is_plausible_api_key(value: str | None) -> bool:
    """Reject empty, truncated, multiline, or whitespace-containing secret values."""
    return bool(
        value
        and len(value) >= 16
        and value.isascii()
        and not any(character.isspace() for character in value)
    )


def write_local_provider_config(
    project_root: Path | None,
    config: LocalProviderConfig,
) -> Path:
    """Atomically write a dedicated local secret file without printing values."""
    path = provider_config_path(project_root)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by code-navi configure-provider; do not commit this file.",
        *(
            f"{key}={json.dumps(value, ensure_ascii=False)}"
            for key, value in config.environment().items()
        ),
        "",
    ]
    temporary = path.with_suffix(".tmp")
    temporary.write_text("\n".join(lines), encoding="utf-8")
    if os.name != "nt":
        temporary.chmod(0o600)
    temporary.replace(path)
    return path


def activate_local_provider_config(config: LocalProviderConfig) -> None:
    """Apply an explicitly saved local configuration to the running process."""
    provider_keys = {
        "CODE_NAVI_PROVIDER",
        "CODE_NAVI_MODEL",
        "OPENAI_API_KEY",
        "DEEPSEEK_API_KEY",
        "DEEPSEEK_MODEL",
        "DEEPSEEK_BASE_URL",
    }
    for key in provider_keys:
        os.environ.pop(key, None)
    os.environ.update(config.environment())


def load_local_provider_config(project_root: Path | None = None) -> Path | None:
    """Load known keys from the ignored file without replacing host environment values."""
    path = provider_config_path(project_root)
    if not path.is_file():
        return None
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        key, separator, encoded = line.partition("=")
        if not separator or key not in _ALLOWED_KEYS:
            raise ProviderConfigurationError(
                f"invalid provider config entry on line {line_number}"
            )
        try:
            value = json.loads(encoded)
        except json.JSONDecodeError as error:
            raise ProviderConfigurationError(
                f"invalid provider config value on line {line_number}"
            ) from error
        if not isinstance(value, str) or not value:
            raise ProviderConfigurationError(
                f"provider config value on line {line_number} must be a string"
            )
        os.environ.setdefault(key, value)
    return path


__all__ = [
    "CONFIG_RELATIVE_PATH",
    "LocalProviderConfig",
    "activate_local_provider_config",
    "load_local_provider_config",
    "is_plausible_api_key",
    "provider_config_path",
    "write_local_provider_config",
]
