"use client";

import { memo, useMemo } from "react";
import katex from "katex";

interface MathSegment {
  type: "text" | "inline-math" | "block-math";
  content: string;
  html?: string;
}

/**
 * Pre-processes text to normalize LaTeX formulas that might be unescaped or
 * missing $...$ wrappers when generated by LLMs.
 */
function normalizeMathDelimiters(rawText: string): string {
  let text = rawText;

  // Replace \[ ... \] with $$ ... $$
  text = text.replace(/\\\[([\s\S]*?)\\\]/g, (_, math) => `$$${math}$$`);

  // Replace \( ... \) with $ ... $
  text = text.replace(/\\\(([\s\S]*?)\\\)/g, (_, math) => `$${math}$`);

  // If text has no $ delimiters, detect common bare LaTeX formulas/commands
  // e.g. y_{i,j,k} = \sigma(...) or bare \sigma, \alpha, \sum_{...}, etc.
  if (!text.includes("$")) {
    // 1. Full formula matching: starts with something like `y_{...}` or `f(x) =` or `\sum...` with operators and backslashes
    // Example: `y_{i,j,k} = \sigma(\sum_{c}\sum_{u,v} w_{u,v,c,k} \cdot x_{i+u,j+v,c} + b_k)`
    text = text.replace(
      /([a-zA-Z]_[a-zA-Z0-9{},\s]+(?:\s*=\s*)[^\n，。！？；）]+|\\[a-zA-Z]+(?:\s*=\s*)[^\n，。！？；）]+)/g,
      (match) => {
        if (match.includes("\\") || match.includes("_") || match.includes("^")) {
          return `$${match.trim()}$`;
        }
        return match;
      },
    );

    // 2. Bare LaTeX Greek letters or math symbols: `\sigma`, `\alpha`, `\beta`, `\theta`, `\lambda`, `\mu`, etc.
    text = text.replace(
      /(?<!\$)\\([a-zA-Z]+)(?![a-zA-Z$])(?![^{]*\})/g,
      (match) => `$${match}$`,
    );
  }

  return text;
}

function parseMathSegments(text: string): MathSegment[] {
  const normalized = normalizeMathDelimiters(text);
  const segments: MathSegment[] = [];

  const regex = /(\$\$[\s\S]+?\$\$|\$[^\$\n]+\$)/g;
  let lastIndex = 0;
  let match: RegExpExecArray | null;

  while ((match = regex.exec(normalized)) !== null) {
    if (match.index > lastIndex) {
      segments.push({
        type: "text",
        content: normalized.slice(lastIndex, match.index),
      });
    }

    const matchedStr = match[0];
    const isBlock = matchedStr.startsWith("$$") && matchedStr.endsWith("$$");
    const mathContent = isBlock
      ? matchedStr.slice(2, -2).trim()
      : matchedStr.slice(1, -1).trim();

    try {
      const html = katex.renderToString(mathContent, {
        displayMode: isBlock,
        throwOnError: false,
        strict: false,
      });
      segments.push({
        type: isBlock ? "block-math" : "inline-math",
        content: mathContent,
        html,
      });
    } catch {
      segments.push({
        type: "text",
        content: matchedStr,
      });
    }

    lastIndex = regex.lastIndex;
  }

  if (lastIndex < normalized.length) {
    segments.push({
      type: "text",
      content: normalized.slice(lastIndex),
    });
  }

  return segments;
}

export const MathContent = memo(function MathContent({
  text,
  className = "",
}: {
  text: string;
  className?: string;
}) {
  const segments = useMemo(() => parseMathSegments(text), [text]);

  return (
    <span className={className}>
      {segments.map((seg, idx) => {
        if (seg.type === "block-math" && seg.html) {
          return (
            <span
              key={idx}
              className="my-2.5 block overflow-x-auto py-1 text-center font-sans text-base leading-relaxed"
              dangerouslySetInnerHTML={{ __html: seg.html }}
            />
          );
        }
        if (seg.type === "inline-math" && seg.html) {
          return (
            <span
              key={idx}
              className="inline-block px-1 align-baseline font-sans text-[0.95em]"
              dangerouslySetInnerHTML={{ __html: seg.html }}
            />
          );
        }
        return <span key={idx}>{seg.content}</span>;
      })}
    </span>
  );
});
